/*
 * loading.java
 *
 * Created on January 13, 2011, 6:44 AM
 */

package ai_mesincuci;

import java.awt.Color;
import javax.swing.JProgressBar;
import javax.swing.JWindow;
import javax.swing.SwingUtilities;
import java.awt.event.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author  sate malmsteen
 */
public class loading extends javax.swing.JDialog {

    /** Creates new form loading */
    public loading(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jam();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mesin.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 280, 320);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kipas.gif"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 70, 220, 210);

        panel.setBackground(new java.awt.Color(204, 0, 0));
        panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel.setLayout(null);
        getContentPane().add(panel);
        panel.setBounds(100, 120, 170, 130);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Simulator Mesin Cuci Front Loading");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 70, 370, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Project 3 Sistem Operasi ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 20, 380, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Dengan Fuzzy Logic Controller ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 110, 300, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("Oleh :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 180, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Group 7 ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 210, 80, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 380);

        setSize(new java.awt.Dimension(730, 379));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
   public void jam() {
       ActionListener taskPerformer = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {  
            if(wkt == 0) {                
                if(s == 0) {
                    dispose();
                    new pilih_baju().setVisible(true);
                    s++;
                }  
            }
            else {
                wkt--;
                if(wkt % 2 == 0) {
                    panel.setBackground(Color.red);
                }
                else {
                    panel.setBackground(Color.blue);
                }
            }
      }
     };   
        new javax.swing.Timer(1000, taskPerformer).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
    int wkt = 5;   
    int s = 0;
}
