/*
 * laundry.java
 *
 * Created on January 12, 2011, 2:37 PM
 */

package ai_mesincuci;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author  sugi
 */
public class pilih_baju extends javax.swing.JFrame {
    
    String[] baju = {"Sutera", "Wol", "Katun"};
    String[] jaket = {"Kulit", "Parasit", "Katun", "Wol"};
    String[] celana = {"Jeans", "Kain"};
            
    /** Creates new form laundry */
    public pilih_baju() {
        initComponents();
        awal();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rbCelana = new javax.swing.JRadioButton();
        rbKaos = new javax.swing.JRadioButton();
        rbJaket = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcbKain = new javax.swing.JComboBox();
        jcbNoda = new javax.swing.JComboBox();
        rbWarna = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbPutih = new javax.swing.JRadioButton();
        rbTidak = new javax.swing.JRadioButton();
        rbYa = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        laundry = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("  Fuzzy Logic - Laundry");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kaos.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 60, 170, 220);

        rbCelana.setBackground(new java.awt.Color(102, 255, 102));
        rbCelana.setText(" Celana");
        rbCelana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCelanaActionPerformed(evt);
            }
        });
        jPanel1.add(rbCelana);
        rbCelana.setBounds(450, 290, 80, 23);

        rbKaos.setBackground(new java.awt.Color(51, 255, 0));
        rbKaos.setText(" Kaos / Baju");
        rbKaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKaosActionPerformed(evt);
            }
        });
        jPanel1.add(rbKaos);
        rbKaos.setBounds(50, 290, 110, 23);

        rbJaket.setBackground(new java.awt.Color(102, 255, 0));
        rbJaket.setText(" Jaket");
        rbJaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJaketActionPerformed(evt);
            }
        });
        jPanel1.add(rbJaket);
        rbJaket.setBounds(270, 290, 100, 23);

        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 560, 310);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jaket.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 60, 170, 220);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/celana.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 60, 170, 220);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Kategori / Model");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(220, 20, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 580, 330);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel3.setText("Jenis Kain");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 20, 80, 20);

        jPanel2.add(jcbKain);
        jcbKain.setBounds(120, 20, 110, 20);

        jcbNoda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Keringat", "Lumpur", "Kecap", "Saos", "Minyak", "Cat", "Lainnya" }));
        jPanel2.add(jcbNoda);
        jcbNoda.setBounds(120, 50, 110, 20);

        rbWarna.setBackground(new java.awt.Color(51, 153, 255));
        rbWarna.setText("Berwarna");
        rbWarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWarnaActionPerformed(evt);
            }
        });
        jPanel2.add(rbWarna);
        rbWarna.setBounds(120, 80, 90, 23);

        jLabel7.setText("Warna Kain");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 80, 80, 20);

        jLabel8.setText("Jenis Noda");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 50, 80, 20);

        rbPutih.setBackground(new java.awt.Color(51, 153, 255));
        rbPutih.setText("Putih");
        rbPutih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPutihActionPerformed(evt);
            }
        });
        jPanel2.add(rbPutih);
        rbPutih.setBounds(210, 80, 60, 23);

        rbTidak.setBackground(new java.awt.Color(51, 153, 255));
        rbTidak.setText("Tidak");
        rbTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTidakActionPerformed(evt);
            }
        });
        jPanel2.add(rbTidak);
        rbTidak.setBounds(120, 110, 60, 23);

        rbYa.setBackground(new java.awt.Color(51, 153, 255));
        rbYa.setText("Ya");
        rbYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbYaActionPerformed(evt);
            }
        });
        jPanel2.add(rbYa);
        rbYa.setBounds(210, 110, 60, 23);

        jLabel9.setText("Kain Pudar");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 110, 80, 20);

        jLabel1.setText("Jumlah");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 140, 90, 20);

        txtJumlah.setText("0");
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahKeyReleased(evt);
            }
        });
        jPanel2.add(txtJumlah);
        txtJumlah.setBounds(120, 140, 30, 20);

        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 10, 270, 160);

        laundry.setBackground(new java.awt.Color(204, 204, 0));
        laundry.setMnemonic('L');
        laundry.setText("Laundry");
        laundry.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        laundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laundryActionPerformed(evt);
            }
        });
        jPanel2.add(laundry);
        laundry.setBounds(290, 180, 80, 20);

        tambah.setBackground(new java.awt.Color(102, 255, 51));
        tambah.setMnemonic('t');
        tambah.setText("Tambah");
        tambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel2.add(tambah);
        tambah.setBounds(210, 180, 70, 20);

        reset.setBackground(new java.awt.Color(153, 153, 255));
        reset.setMnemonic('R');
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset);
        reset.setBounds(10, 180, 70, 20);

        tblData.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model", "Kain", "Noda", "Warna", "Pudar", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(290, 10, 280, 160);

        hapus.setBackground(new java.awt.Color(255, 51, 0));
        hapus.setMnemonic('h');
        hapus.setText("Hapus");
        hapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel2.add(hapus);
        hapus.setBounds(500, 180, 70, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 340, 580, 220);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 650, 570);

        setSize(new java.awt.Dimension(606, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void rbKaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKaosActionPerformed
    rbKaos.setSelected(true);
    rbJaket.setSelected(false);
    rbCelana.setSelected(false);
    
    int a = jcbKain.getItemCount();
    jcbKain.removeAllItems();    
    for (int i = 0; i < baju.length; i++) {
        jcbKain.addItem(baju[i]);
    }
}//GEN-LAST:event_rbKaosActionPerformed

private void rbJaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJaketActionPerformed
    rbKaos.setSelected(false);
    rbJaket.setSelected(true);
    rbCelana.setSelected(false);
    
    int a = jcbKain.getItemCount();
    jcbKain.removeAllItems();
    for (int i = 0; i < jaket.length; i++) {
        jcbKain.addItem(jaket[i]);
    }
}//GEN-LAST:event_rbJaketActionPerformed

private void rbCelanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCelanaActionPerformed
    rbKaos.setSelected(false);
    rbJaket.setSelected(false);
    rbCelana.setSelected(true);
    
    int a = jcbKain.getItemCount();
    jcbKain.removeAllItems();
    for (int i = 0; i < celana.length; i++) {
        jcbKain.addItem(celana[i]);
    }
}//GEN-LAST:event_rbCelanaActionPerformed

private void rbWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWarnaActionPerformed
    rbWarna.setSelected(true);
    rbPutih.setSelected(false);
}//GEN-LAST:event_rbWarnaActionPerformed

private void rbPutihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPutihActionPerformed
    rbWarna.setSelected(false);
    rbPutih.setSelected(true);
}//GEN-LAST:event_rbPutihActionPerformed

private void rbTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTidakActionPerformed
    rbTidak.setSelected(true);
    rbYa.setSelected(false);
}//GEN-LAST:event_rbTidakActionPerformed

private void rbYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbYaActionPerformed
    rbTidak.setSelected(false);
    rbYa.setSelected(true);
}//GEN-LAST:event_rbYaActionPerformed

private void txtJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyReleased
     String kata = txtJumlah.getText();       
        String tmp = "";

        if(kata.length() > 2) {
            for(int i=0; i<2; i++) {
                tmp += ""+kata.charAt(i);
            }
            txtJumlah.setText(tmp);
        }
        else {
            try {
                if(kata.equalsIgnoreCase("") || kata.equalsIgnoreCase(" ")) {}
                else {
                    int check = Integer.parseInt(kata);
                }
            }
            catch(Exception e) {
                int stas = kata.length()-1;
                for(int i=0; i<stas; i++) {
                    tmp += ""+kata.charAt(i);
                }
                txtJumlah.setText(tmp);
            }
        }
}//GEN-LAST:event_txtJumlahKeyReleased

private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
    try {
        int jumlah = Integer.parseInt(txtJumlah.getText());
        if(jumlah <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah Pakaian Harus Di Atas 0..",
                    "NoStok", JOptionPane.WARNING_MESSAGE);
        }
        else if(jumlah > 15) {
            JOptionPane.showMessageDialog(this, "Jumlah Pakaian Harus Di Bawah 15..",
                    "StokOver", JOptionPane.WARNING_MESSAGE);
            txtJumlah.setText("0");
        }
        else {
            String model = "";
            if(rbCelana.isSelected()) {
                model = "C";
            }
            else if(rbJaket.isSelected()) {
                model = "J";
            }
            else {
                model = "K";
            }
            
            String warna = "";
            if(rbPutih.isSelected()) {
                warna = "P";
            }
            else {
                warna = "W";
            }
            
            String pudar = "";
            if(rbYa.isSelected()) {
                pudar = "Y";
            }
            else {
                pudar = "T";
            }
            
            javax.swing.table.DefaultTableModel Model = ((javax.swing.table.DefaultTableModel)tblData.getModel());
            Model.addRow(new String [] {
                   model,
                   jcbKain.getSelectedItem().toString().trim(),
                   jcbNoda.getSelectedItem().toString().trim(),
                   warna,
                   pudar,
                   txtJumlah.getText()
            });
            atur();
        }
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error Pada : \n"+e, "Tambah", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_tambahActionPerformed

private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
    try {
        int a = tblData.getSelectedRow();
        if(tblData.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(this, "Data Belum Ada..",
                    "Hapus", JOptionPane.WARNING_MESSAGE);
        }
        else if(a<0) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Baris Data Yang Akan Di Hapus..",
                    "Hapus", JOptionPane.WARNING_MESSAGE);
        }
        else {
            javax.swing.table.DefaultTableModel Model = ((javax.swing.table.DefaultTableModel)tblData.getModel());
            Model.removeRow(a);
            atur();
        }
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error Pada : \n"+e, "Hapus", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_hapusActionPerformed

private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
    awal();
}//GEN-LAST:event_resetActionPerformed

private void laundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laundryActionPerformed
    try {
        if(tblData.getRowCount() <= 0) {
             JOptionPane.showMessageDialog(this, "Data Belum Ada..",
                    "Laundry", JOptionPane.WARNING_MESSAGE);
        }
        else {
            String data[][] = new String [tblData.getRowCount()] [6];
            for (int i = 0; i < data.length; i++) {
                data[i][0] = tblData.getValueAt(i, 0).toString().trim();
                data[i][1] = tblData.getValueAt(i, 1).toString().trim();
                data[i][2] = tblData.getValueAt(i, 2).toString().trim();
                data[i][3] = tblData.getValueAt(i, 3).toString().trim();
                data[i][4] = tblData.getValueAt(i, 4).toString().trim();
                data[i][5] = tblData.getValueAt(i, 5).toString().trim();
            }            
            ls.set_laundry(data, this);
        }
    }
    catch(Exception e) {
        e.printStackTrace();
        //JOptionPane.showMessageDialog(this, "Error Pada : \n"+e, "Laundry", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_laundryActionPerformed
    
    public void awal() {
        try {
            rbKaos.setSelected(true);
            int a = jcbKain.getItemCount();
            jcbKain.removeAllItems();    
            for (int i = 0; i < baju.length; i++) {
                jcbKain.addItem(baju[i]);
            }
            jcbNoda.setSelectedIndex(0);
            rbKaos.setSelected(true);
            rbJaket.setSelected(false);
            rbCelana.setSelected(false);
            rbWarna.setSelected(true);
            rbPutih.setSelected(false);
            rbTidak.setSelected(true);
            rbYa.setSelected(false);
            txtJumlah.setText("0");
            
            javax.swing.table.DefaultTableModel Model = ((javax.swing.table.DefaultTableModel)tblData.getModel());
                int row = Model.getRowCount();
                for (int i = 0; i < row; i++) {
                    Model.removeRow(0);
                }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error Pada : \n"+e, "Awal", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     public void atur() {
        javax.swing.table.DefaultTableModel Model = ((javax.swing.table.DefaultTableModel)tblData.getModel());
        DefaultTableCellRenderer ren = new DefaultTableCellRenderer();             
        ren.setHorizontalAlignment(JLabel.CENTER);
        TableColumnModel tcm = tblData.getColumnModel();
        tcm.getColumn(0).setCellRenderer(ren);       
        tcm.getColumn(1).setCellRenderer(ren);
        tcm.getColumn(2).setCellRenderer(ren);
        tcm.getColumn(3).setCellRenderer(ren);
        tcm.getColumn(4).setCellRenderer(ren);
        tcm.getColumn(5).setCellRenderer(ren);
        tblData.setAutoscrolls(true);    
        tblData.updateUI();        
    }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbKain;
    private javax.swing.JComboBox jcbNoda;
    private javax.swing.JButton laundry;
    private javax.swing.JRadioButton rbCelana;
    private javax.swing.JRadioButton rbJaket;
    private javax.swing.JRadioButton rbKaos;
    private javax.swing.JRadioButton rbPutih;
    private javax.swing.JRadioButton rbTidak;
    private javax.swing.JRadioButton rbWarna;
    private javax.swing.JRadioButton rbYa;
    private javax.swing.JButton reset;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
    laundry_set ls = new laundry_set();
}
